<?php $this->headLink()->appendStylesheet($this->baseUrl('media/css/jquery.treeTable.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('media/js/jquery.cookie.js', 'text/javascript')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('media/js/jquery.treeTable.js', 'text/javascript')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('media/js/erga/apasxoloumenoi/view.js', 'text/javascript')); ?>
<?php echo $this->projectNavigation(array(), $this->getProject()); ?>
<br />
<?php echo $this->form ?>
<br />
<input type="text" id="id_search" placeholder=" Αναζήτηση..."></input>

<div id="listaUpoergwn">


<table id="apasxoloumenoicollapsible" class="treeTable fatTable">
    <thead>
    <tr>
        <th width="16"></th>
        <th>Όνομα</th>
        <th>Ημερομηνία Έναρξης</th>
        <th>Ημερομηνία Λήξης</th>
        <th>Ποσό Σύμβασης</th>
        <th id="apasxoloumenoi-view-plhrwteo">Πληρωτέο</th>
        <th width="65">Ενέργειες</th>
    </tr>
    </thead>
    <tbody>
    <?php if($this->project->get_iscomplex() == 1) {
        ?>
        <tr id="project" class="projectRow expanded">
            <td>

            </td>
            <td>
                <?php echo $this->project->get_basicdetails()->get_title(); ?>
            </td>
            <td>

            </td>
            <td>

            </td>
            <td>

            </td>
            <td>

            </td>
            <td>
                <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'new', 'projectid' => $this->project->get_projectid()), null, true); ?>"
                   ><img src="<?php echo $this->baseUrl('images/add3.png'); ?>" alt="προσθήκη" title="Προσθήκη Νέου Απασχολούμενου" class="addNew"/>
                </a>
            </td>
        </tr>
    <?php } ?>
    <?php foreach($this->project->get_subprojects() as $curSubProject) {
        if($this->project->get_iscomplex() == 1) {
            $class = "subproject child-of-project";
        } else {
            $class = "subproject expanded";
        }
        ?>
        <tr id="subproject<?php echo $curSubProject->get_subprojectid(); ?>" class="<?php echo $class; ?>">
            <td>
                <?php
                    /*if($curSubProject->get_subprojectdirectlabor() == 1) { ?>
                <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Apasxoloumenoi', 'action' => 'exportemployees', 'subprojectid' => $curSubProject->get_subprojectid()), null, true); ?>">
                    <img src="<?php echo $this->baseUrl('images/icons/docicon.png'); ?>" alt="ΕξαγωγήDoc" title="Εξαγωγή σε Doc" />
                </a>
                <?php }*/ ?>
            </td>
            <td>
                <?php
                    if($curSubProject->get_subprojectdirectlabor() == 1) {
                        echo '<strong>[A]</strong> ';
                    }
                    echo $curSubProject->get_subprojecttitle();
                    echo ' ('.$curSubProject->get_subprojectnumber().')';
                ?>
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
            <td>

            </td>
            <td>
                <?php if($curSubProject->get_subprojectdirectlabor() == 1) { ?>
                <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'new', 'subprojectid' => $curSubProject->get_subprojectid()), null, true); ?>"
                   ><img src="<?php echo $this->baseUrl('images/add3.png'); ?>" alt="προσθήκη" title="Προσθήκη Νέου Απασχολούμενου" class="addNew"/>
                </a>
                <?php } else { ?>
                <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'newcontractor', 'subprojectid' => $curSubProject->get_subprojectid()), null, true); ?>"
                   ><img src="<?php echo $this->baseUrl('images/add3.png'); ?>" alt="προσθήκη" title="Προσθήκη Νέου Αναδόχου" class="addNew"/>
                </a>
                <?php } ?>
            </td>
        </tr>
        <?php if($curSubProject->get_subprojectdirectlabor() == "1") {
                foreach($curSubProject->get_employees() as $curSupervisor) {
                    echo $this->partial('apasxoloumenoi/partial/employee.phtml', 'erga', array('employee' => $curSupervisor, 'subproject' => $curSubProject));
                }
            } else {
                foreach($curSubProject->get_contractors() as $curSupervisor) {
                    echo $this->partial('apasxoloumenoi/partial/contractor.phtml', 'erga', array('contractor' => $curSupervisor, 'subproject' => $curSubProject));
                }
            } ?>
    <?php } ?>
    <?php foreach($this->project->get_thisprojectemployees() as $curSupervisor) {
        echo $this->partial('apasxoloumenoi/partial/employee.phtml', 'erga', array('employee' => $curSupervisor, 'project' => $this->project));
    } ?>
    </tbody>
        </table>
        </div>
<br />