<?php $this->headScript()->appendFile($this->baseUrl('media/js/erga/ergaview.js', 'text/javascript')); ?>
<?php echo $this->filterform; ?>
<div id="rss">
<a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'rss', 'token' => $this->user->get_token())); ?>" class="feed"><img src="<?php echo $this->baseUrl('images/rss.png'); ?>" alt="RSS" title="RSS" /></a>
<a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'atom', 'token' => $this->user->get_token())); ?>" class="feed"><img src="<?php echo $this->baseUrl('images/atom.png'); ?>" alt="Atom" title="Atom" /></a>
</div>
<?php echo $this->viewErga($this->entries, $this->type, false); ?>
<br/>
<?php if(!is_array($this->filters)) { $this->filters = array(); } ?>
<a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'export')); ?>" class="excel">Εξαγωγή πίνακα σε Excel</a>