<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <title>Επισκόπηση</title>

    <link href="<?php echo $this->baseUrl('media/css/overview.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('media/css/overviewPrint.css'); ?>" media="print" rel="stylesheet"  type="text/css"   />
</head>
<body>
<div id="wrap">
<div id="a4">
<table class="analutikos fatTable">

    <thead><tr><th>Βασικά Στοιχεία Υποέργου</th></tr></thead>
    <tbody class="bigwidth">
    <tr>
        <td>
            Έργο:

        </td>
        <td>
            <?php echo $this->project->get_parentproject()->get_basicdetails()->get_title(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Κωδικός Έργου:

        </td>
        <td>
            <?php echo $this->project->get_parentproject()->get_basicdetails()->get_mis(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Τίτλος Υποέργου 1:
        </td>
        <td>
            <?php echo $this->project->get_subprojecttitle(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Τίτλος Υποέργου 2:

        </td>
        <td>
            <?php echo $this->project->get_subprojecttitleen(); ?>
        </td>
    </tr>

    <tr>
        <td>
            Προϋπολογισμός Έργου:

        </td>

        <td>
            <?php echo $this->project->get_subprojectbudget(); ?>
        </td>
    </tr>

    <tr>
        <td>
            ΦΠΑ:
        </td>

        <td>
            <?php echo $this->project->get_subprojectbudgetfpa(); ?>
        </td>
    </tr>

    <tr>
        <td>
            Σύνολο (με ΦΠΑ):

        </td>

        <td>
            <?php echo $this->project->get_subprojectbudgetwithfpa(); ?>
        </td>
    </tr>

    <tr>
        <td>
            Ημερομηνία Έναρξης/Λήξης:

        </td>
        <td>
            <?php echo $this->project->get_subprojectstartdate().' &ndash; '.$this->project->get_subprojectenddate(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Επιστημονικά Υπεύθυνος:
        </td>

        <td>
            <?php echo $this->project->get_subprojectsupervisor()->get_realnameLowercase(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Φορέας Χρηματοδότησης:
        </td>

        <td>
            <?php echo $this->project->get_parentproject()->get_financialdetails()->get_fundingagenciesAsString(); ?>
        </td>
    </tr>

    <tr>
        <td>
            Κατηγορία:
        </td>

        <td>
            <?php echo $this->project->get_parentproject()->get_basicdetails()->get_category()->get_name(); ?>
        </td>
    </tr>




    </tbody>


</table>

<?php if($this->project->get_contractors()->count() > 0) { ?>
<table class="analutikos fatTable">
    <thead><tr><th>Ανάδοχοι</th></tr></thead>
    <tbody>
        <?php
        echo '
    <tr class="title">
        <td>
          Επωνυμία
        </td>
        <td>
          ΑΦΜ
        </td>
        <td>
          Διάρκεια
        </td>
        <td>
          Ποσό Σύμβασης
        </td>
        <td>
          Κατάσταση
        </td>
    </tr>
        ';
        foreach($this->project->get_contractors() as $curSupervisor) {
            echo '
    <tr>
        <td>
            '.$curSupervisor->get_agency()->get_name().'
        </td>
        <td>
            '.$curSupervisor->get_agency()->get_afm().'
        </td>
        <td>
            '.$curSupervisor->get_startdate().' &ndash; '.$curSupervisor->get_enddate().'
        </td>
        <td>
           '.$curSupervisor->get_amount().'
        </td>
        <td>
            '.$this->getContractorStageText($curSupervisor).'
        </td>
    </tr>
        ';
        }
        ?>
    </tbody>
</table>
    <?php } ?>

<?php if(count($this->project->get_employees()) > 0) { ?>
<table class="analutikos fatTable">
<tr><th>Απασχολούμενοι</th></tr>
</table>
<table class="analutikos fatTable">
  <tbody>
  <?php
           echo '
    <tr class="title">
        <td>
          Υπ
        </td>
        <td>
          Ονοματεπώνυμο
        </td>
        <td>
          ΑΦΜ
        </td>
        <td>
          Διάρκεια
        </td>
        <td>
          Ποσό Σύμβασης
        </td>
    </tr>
        ';
          foreach($this->project->get_employees() as $curSupervisor) {
                echo '
    <tr>
        <td>
            '.($curSupervisor->get_subproject() != null ? '<span title="'.$curSupervisor->get_subproject()->get_subprojecttitle().'" class="tooltip">'.$curSupervisor->get_subproject()->get_subprojectnumber().'</span>' : '-').'
        </td>
        <td>
            '.$curSupervisor->get_employee()->get_name().'
        </td>
        <td>
            '.$curSupervisor->get_employee()->get_afm().'
        </td>
        <td>
            '.$curSupervisor->get_startdate().' &ndash; '.$curSupervisor->get_enddate().'
        </td>

  <td>
       '.$curSupervisor->get_amount().'
  </td>
    </tr>
        ';
          }
  ?>
  </tbody>
    <?php
    if($this->project->get_iscomplex() == 1) {
        ?>
</table>
<?php }
} ?>

<?php echo $this->partial('diaxeirisi/partial/aporofisi.phtml', 'erga', array('tworkpackages' => $this->tworkpackages, 'tcategories' => $this->tcategories)); ?>
<table class="analutikos fatTable">
<tr><th>Παραδοτέα</th></tr>
</table>
<table class="analutikos fatTable">
    <tbody>
    <tr class="title">
        <td>
        ΠΕ
        </td>
        <td>
        Παραδοτέο
        </td>
        <td>
        Διάρκεια
        </td>
        <td>
        Ποσό
        </td>
        <td>
        Κατάσταση
        </td>
        <td>
        Συντάκτες / Ανάδοχος
        </td>

    </tr>
    <?php
      foreach($this->project->get_workpackagesNatsort() as $curWorkPackage) {
          foreach($curWorkPackage->get_deliverablesNatsort() as $curDeliverable) {
              echo '
      <tr>
          <td>
              '.$curDeliverable->get_workpackage()->get_workpackagecodename().'
          </td>
          <td style="min-width: 220px;">
              '.$curDeliverable->__toString().'
          </td>
          <td>
              '.$curDeliverable->get_startdate().' – '.$curDeliverable->get_enddate().'
          </td>
          <td>
              '.$curDeliverable->get_amount().'
          </td>
          <td>
             '.$this->getCompletionText($curDeliverable).'
          </td>
          <td>
             '.$this->printDeliverableAuthors($curDeliverable).'
          </td>
      </tr>';
          }
      }
    ?>
    </tbody>
</table>

<!--<p><input  type="button" name="printbutton" value="Print Document" onClick="parent.print()"></p>-->

</div>
</div>


</body>
</html>