<tr id="contractor<?php echo $this->contractor->get_recordid(); ?>" class="contractor child-of-subproject<?php echo $this->subproject->get_subprojectid(); ?>">
    <td>

    </td>
    <td>
        <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'reviewcontractor', 'contractorid' => $this->contractor->get_recordid()), null, true); ?>">
            <?php echo $this->contractor->get_agency()->get_name(); ?>
        </a>
    </td>
    <td>
        <?php echo $this->contractor->get_startdate(); ?>
    </td>
    <td>
        <?php echo $this->contractor->get_enddate(); ?>
    </td>
    <td>
        <?php echo $this->contractor->get_amount(); ?>
    </td>
    <td>
        <a href="javascript:void(0);" onclick="if( prompt('Θέλετε σίγουρα να διαγράψετε τον ανάδοχο <?php echo $this->contractor->get_agency()->get_name(); ?>', 'Παρακαλώ πληκτρολογήστε ΝΑΙ για να συνεχίσετε...') == 'ΝΑΙ'  ) { window.location = '<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Apasxoloumenoi', 'action' => 'deletecontractor', 'contractorid' => $this->contractor->get_recordid(), 'return' => urlencode($this->getCurrentUrl())), null, true); ?>' }">
            <img src="<?php echo $this->baseUrl('images/delete_x.gif'); ?>" alt="Διαγραφή" title='Διαγραφή Αναδόχου' class="alone"/>
        </a>
    </td>
</tr>