<?php echo $this->filterform; ?>
<table id="apasxoloumenoitable" class="thinTable">
    <thead>
        <tr>
            <th><?php echo $this->getOrderLink('name', 'Ονοματεπώνυμο'); ?></th>
            <th><?php echo $this->getOrderLink('projectscount', 'Αριθμός Έργων'); ?></th>
            <th><?php echo $this->getOrderLink('subprojectscount', 'Αριθμός Υποέργων'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach($this->supervisors as $curSupervisor) {
            // Η μορφή του $curEmployee είναι στο documentation της κλάσης Erga_Model_Repositories_SubProjectEmployees
            // στη μέθοδο getTotalEmployeesList
            echo '<tr>';
            echo '<td><a href="'.$this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'overview', 'id' => $curSupervisor[0]->get_userid(), 'currentprojects' => $this->filters['currentprojects']), null, true).'" title="Επισκόπηση απασχολούμενου">
                          <img src="'.$this->baseUrl('images/overview.png').'" alt="review" /> '.$curSupervisor[0]->get_realnameLowercase().'
                       </a>
                  </td>';
            echo '<td>'.$curSupervisor['projectscount'].'</td>';
            echo '<td>'.Zend_Registry::get('entityManager')->getRepository('Application_Model_User')->getSupervisorSubProjectsCount($curSupervisor[0], $this->filters).'</td>';
            echo '</tr>';
        }
        ?>
    </tbody>
</table>
<?php
// Links σελίδων (pagination)
echo $this->supervisors->__toString();
?>
<br/>
<a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => $this->getControllerName(), 'action' => 'export')); ?>" class="excel">Εξαγωγή πίνακα σε Excel</a>