<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href='<?php echo $this->baseUrl("elke-index/style.css"); ?>'>


</head>
<body>
<div class="login_box">
    <div class="lb_content">
        <h2 class="lb_ribbon lb_blue"><span>Ειδικός Λογαριασμός Κονδυλίων Έρευνας</span></h2>


        <div id="loginForm">
            <?php echo $this->form ?>
        </div>


        <img src="<?php echo $this->baseUrl('/elke-index/images/footer_logo.png')?>" alt="logo" class=logo>
        <small style="display: block; white-space: nowrap;">
            <hr />
            Η εφαρμογή Διαχείρισης Ερευνητικών Προγραμμάτων του ΤΕΙ Αθήνας<BR />
            αναπτύχθηκε στο πλαίσιο της πράξης «Ψηφιακές Υπηρεσίες του ΤΕΙ<BR />
            Αθήνας» με MIS 327694, η οποία χρηματοδοτήθηκε από το Επιχειρησιακό<BR />
            Πρόγραμμα της Ψηφιακής Σύγκλισης
        </small>
    </div>
</div>
</div>


</body>
</html>
