<?php
echo $this->doctype();
$userObject = $this->getUserInfo();
$front = Zend_Controller_Front::getInstance();
$config = $front->getParam('bootstrap')->getOptions();
$request = $front->getRequest();
$this->messages = array_merge(Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->getMessages(), Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->getCurrentMessages());
?>

<html>
<head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta http-equiv="Content-Language" content="el">
        <title>Ειδικός Λογαριασμός Κονδυλίων Έρευνας</title>
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" type='text/javascript'></script>
	<![endif]-->
        <?php $this->headLink()->appendStylesheet($this->baseUrl('media/css/global.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl('images/start/jquery-ui-1.8.12.custom.css')); ?>
		<?php $this->headLink(array('rel' => 'favicon',
                                  'href' => 'favicon.ico'),
                                  'PREPEND'); ?>
        <?php echo $this->headLink(); ?>
        <script type="text/javascript">
            userLoggedIn = <?php if($userObject != false) { echo 'true'; } else { echo 'false'; } ?>;
            sessionTimeout = <?php echo ini_get('session.gc_maxlifetime')*1000; ?>;
            baseUrl = "<?php echo $this->baseUrl(); ?>";
        </script>
        <?php
            // ΠΡΟΣΟΧΗ: Αυτά τα scripts εμφανίζονται με σειρά από κάτω προς το πάνω
            $this->headScript()->prependFile($this->baseUrl("media/js/dialog.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/main.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.idle-timer.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.dropdownPlain.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.h5validate.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.tabify.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.qtip.js"));
			$this->headScript()->prependFile($this->baseUrl("media/js/jquery.numberformatter-1.2.2.min.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jshashtable.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.textarea-expander.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.quicksearch.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.tablesorter.min.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.collapsible-v.2.1.3.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery-ui-1.8.16.custom.min.js"));
            $this->headScript()->prependFile($this->baseUrl("media/js/jquery.js"));


        ?>
        </head>
        <body>
        <div id="page" align="center">
          <div id="header">
            <nav>
                <?php $this->navigation()->menu()->renderMenu(null,array('maxDepth' => 0)); ?>
                <?php $this->navigation()->menu()->setPartial('sidebar.phtml'); ?>
                <?php echo $this->navigation()->menu()->render(); ?>


                <div class="navfooter">
                    <?php
                    $session = $this->getNextSession();
                    if($session != null) { ?>
                    <div id="nextsunedriasi">

                        <div>Επόμενη Συνεδρίαση</div>
                        <div>
                        <?php
                            $opts = array('module' => 'synedriaseisee', 'controller' => 'index', 'action' => 'eventview', 'id' => $session->get_id());
                            echo '<a href="'.$this->url($opts, 'default').'">'.$session->__toString().'</a>';
                            echo '<a href="'.$this->url($opts+array('print' => 'true'), 'default').'"><img src="'.$this->baseUrl().'/images/print.gif" alt="Εκτυπώσιμη μορφή" title="Εκτυπώσιμη μορφή" /></a>';
                        ?>
                        </div>
                    </div>

                    <?php } ?>

                </div>
            </nav>
            </div>
          </div>
          <div class="main">
               <div id="mainHeader">
                   <?php
                    if(!isset($this->breadcrumbs)) {
                        // Αν δεν υπάρχουν ειδικά breacrumbs τότε ορίζουμε null και γίνονται render με βάση το default navigation container
                        $this->breadcrumbs = null;
                    }
                    $breadcrumbs = $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(false)->setRenderInvisible(true)->render($this->breadcrumbs);
                    if($breadcrumbs != "") {
                        echo $breadcrumbs;
                    } else {
                        echo 'Ειδικός Λογαριασμος Κονδυλίων Έρευνας';
                    }
                   ?>
                   <div id="loginLink">
              <?php
                                    if($userObject != false) {
                                        echo $userObject->get_realnameLowercase().'<BR>';
                                        if($userObject->hasRole('professor')) {
                                            echo '<a href="'.$this->url(array('module' => 'default', 'controller' => 'Profile', 'action' => 'index'), 'default', true).'">Προφίλ</a> | ';
                                        }
                                        echo '<a href="'.$this->url(array('module' => 'default', 'controller' => 'Login', 'action' => 'logout'), 'default', true).'">Αποσύνδεση</a>';
                                    } else {
                                        echo '<a href="'.$this->url(array('module' => 'default', 'controller' => 'Login'), 'default', true).'">Σύνδεση</a>';
                                    }
            ?>
            </div>
    </div>

              <div id="mainWrapper">
                  <?php if($this->pageTitle != "") { ?>
                     <h2 id="pageTitle">
                         <?php echo $this->pageTitle; ?>
                     </h2>
                  <?php } ?>


            <?php if (count($this->messages)) : ?>
            <div class="flashmessages">
                <ul id="flashmessages">
                <?php foreach ($this->messages as $message) : ?>
                    <?php if(is_array($message) && isset($message['error'])) { $error = true; $message = $message['error']; } ?>
                    <li<?php if(isset($error)) { echo ' class="error"'; } ?>><?php echo $this->escape($message); ?></li>
                    <?php unset($error); ?>
                <?php endforeach; ?>
                </ul>
            </div>
            <?php endif; ?>
            <div><?php echo $this->layout()->content ?></div>
            </div>
            <footer>
                <a href="#" id="linktotop"><?php  echo '<img src="'.$this->baseUrl().'/images/top.png" alt="to top" title="to top"/>'; ?></a>

               <?php if(isset($config['report']) && isset($config['report']['redmineUrl'])) { ?>
                   <?php if($userObject != false) { ?>
                        <a href='<?php echo $this->url(array('module' => 'default', 'controller' => 'Report', 'action' => 'index'), 'default', true); ?>' id="report">Αναφορά Προβλήματος</a><br />
                   <?php } else { ?>
                        <span title="Μόνο για αυθεντικοποιημένους χρήστες" id="report">Αναφορά Προβλήματος</span><br />
                   <?php } ?>
               <?php } ?>
               <a href='<?php echo $this->getHelpUrl($request); ?>' id="help">Βοήθεια</a><br />
               <a href='<?php echo $this->baseUrl('help/api/') ?>' id="help">API</a><br />
               <a href='mailto:eee@teiath.gr' id="help">Επικοινωνία</a>
               <div id="logos">
                          <?php  echo '<img src="'.$this->baseUrl().'/images/logos/tei.png" alt="Λογότυπο" title="Λογότυπο" class=logo />'; ?>
                          <?php  echo '<img src="'.$this->baseUrl().'/images/logos/eurwpaikienwsi.jpg" alt="Λογότυπο" title="Λογότυπο" class=logo />'; ?>
                          <?php  echo '<img src="'.$this->baseUrl().'/images/logos/psifiakiellada.JPG" alt="Λογότυπο" title="Λογότυπο" class=logo />'; ?>
                          <?php  echo '<img src="'.$this->baseUrl().'/images/logos/epsa_logo_CMYK.png" alt="Λογότυπο" title="Λογότυπο" class=logo />'; ?>
                </div>
            </footer>

        </div>
<?php echo $this->headScript(); ?>
</body>
</html>
