<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />

<title>Επισκόπηση Απασχολούμενου</title>

<link href="<?php echo $this->baseUrl('media/css/overview.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('media/css/overviewPrint.css'); ?>" media="print" rel="stylesheet" type="text/css"   />

</head>
<body>
<div id="wrap">
<div id="a4">
<table class="analutikos">
  <thead><tr><th>Στοιχεία Απασχολούμενου</th></tr></thead>
    <tbody class="bigwidth">
    <tr>
        <td>
            Ονοματεπώνυμο:
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_name(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Διεύθυνση Κατοικίας (οδός, αριθμός, ΤΚ, πόλη):
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_address(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Α.Δ.Τ.:
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_adt(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Α.Φ.Μ.:
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_afm(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Δ.Ο.Υ.:
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_doy(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Τηλέφωνο.:
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_phone(); ?>
        </td>
    </tr>
    <tr>
        <td>
            E-Mail:
        </td>
        <td>
            <?php echo $this->employee[0]->get_employee()->get_email(); ?>
        </td>
    </tr>
    <tr>
        <td>
            Συνολική Αμοιβή:
        </td>
        <td>
            <?php echo Zend_Locale_Format::toNumber($this->employee['totalamount'],array('precision' => 2,'locale' => Zend_Registry::get('Zend_Locale'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<table class="analutikos">
    <thead>
        <tr><th>Συμβάσεις</th></tr>
    </thead>
    <tbody class="bigwidth">
        <tr class="title">
            <td>
              Τίτλος Έργου
            </td>
            <td>
              Υπ.
            </td>
            <td>
              Αριθμός Σύμβασης
            </td>
            <td>
              Διάρκεια Σύμβασης
            </td>
            <td>
              Ποσό Σύμβασης
            </td>
        </tr>
        <?php
        foreach($this->symvaseis as $curSymvasi) {
            echo $this->partial('apasxoloumenoi/partial/projects.phtml', 'anafores', array('employee' => $this->employee[0], 'curSymvasi' => $curSymvasi));
        }
        ?>
    </tbody>
</table>
<table class="analutikos">
    <thead>
        <tr><th>Παραδοτέα</th></tr>
    </thead>
    <tbody class="bigwidth">
        <tr class="title">
            <td>
              Τίτλος Έργου
            </td>
            <td>
              Υπ.
            </td>
            <td>
              ΠΕ
            </td>
            <td>
              Παραδοτέο
            </td>
            <td>
              Διάρκεια
            </td>
            <td>
              Ποσό
            </td>
            <td>
              Κατάσταση
            </td>
        </tr>
        <?php foreach($this->deliverables as $curDeliverable) { ?>
        <?php $curSubproject = $curDeliverable->get_workpackage()->get_subproject(); ?>
        <tr>
            <td>
                <?php echo $curDeliverable->get_workpackage()->get_subproject()->get_parentproject()->get_basicdetails()->get_shorttitle(); ?>
            </td>
            <td>
                <span title="<?php echo $curSubproject->get_subprojecttitle() ?>" class="tooltip"><?php echo $curSubproject->get_subprojectnumber(); ?></span>
            </td>
            <td>
                <span title="<?php echo $curDeliverable->get_workpackage()->get_workpackagename(); ?>" class="tooltip"><?php echo $curDeliverable->get_workpackage()->get_workpackagecodename(); ?></span>
            </td>
            <td>
                <span title="<?php echo $curDeliverable->get_title(); ?>" class="tooltip"><?php echo $curDeliverable->get_codename(); ?></span>
            </td>
            <td>
               <?php echo $curDeliverable->get_startdate().' &ndash; '.$curDeliverable->get_enddate(); ?>
            </td>
            <td>
               <?php if($curDeliverable->get_authors()->count() <= 1 && $curDeliverable->get_authors()->get(0)->get_rate() == null) { echo $curDeliverable->get_amount(); } else { echo '-'; } ?>
            </td>
            <td>
               <?php echo $this->getCompletionText($curDeliverable); ?>
            </td>
            <td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</div>
</div>
</body>
</html>