<?php
if($this->curSymvasi->get_subproject() != null) {
    $this->curProject = $this->curSymvasi->get_subproject();
} else if($this->curSymvasi->get_project() != null) {
    $this->curProject = $this->curSymvasi->get_project();
}
if($this->curProject instanceof Erga_Model_SubProject) {
    $projectname = $this->curProject->get_parentproject()->__toString();
    $subprojectnumber = '<span title="'.$this->curProject->get_subprojecttitle().'" class="tooltip">'.$this->curProject->get_subprojectnumber().'</span>';
    //$budget = $this->curProject->get_subprojectbudget();
} else if($this->curProject instanceof Erga_Model_Project) {
    $projectname = $this->curProject->__toString();
    $subprojectnumber = '-';
    //$budget = $this->curProject->get_financialdetails()->get_budget();
}
$curSymvasi = $this->curSymvasi;
?>
<tr>
    <td>
        <?php echo $projectname; ?>
    </td>
    <td>
        <?php echo $subprojectnumber; ?>
    </td>
    <td>
        <?php echo $curSymvasi->get_contractnum(); ?>
    </td>
    <td>
        <?php echo $curSymvasi->get_startdate().' &ndash; '.$curSymvasi->get_enddate(); ?>
    </td>
    <td>
        <?php echo $curSymvasi->get_amount(); ?>
    </td>
    <td>
</tr>