<ul class="reports">
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Professor_Apasxoloumenoi', 'action' => 'index'), null, true); ?>">Απασχολούμενοι</a>
</li>
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Professor_Fylla', 'action' => 'index'), null, true); ?>">Στατιστικά Μηναίων Φύλλων Παρακολούθησης</a>
</li>
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Professor_Anadoxoi', 'action' => 'index'), null, true); ?>">Ανάδοχοι</a>
</li>
</ul>