<ul class="reports">
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Apasxoloumenoi', 'action' => 'index'), null, true); ?>">Απασχολούμενοι</a>
</li>
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Fylla', 'action' => 'index'), null, true); ?>">Στατιστικά Μηναίων Φύλλων Παρακολούθησης</a>
</li>
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Anadoxoi', 'action' => 'index'), null, true); ?>">Ανάδοχοι</a>
</li>
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Epistimonikaypeuthinoi', 'action' => 'index'), null, true); ?>">Επιστημονικά Υπεύθυνοι</a>
</li>
<li>
    <a href="<?php echo $this->url(array('module' => $this->getModuleName(), 'controller' => 'Ekprothesma', 'action' => 'index'), null, true); ?>">Εκπρόθεσμα Παραδοτέα</a>
</li>

</ul>
