<?php

namespace DoctrineProxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Erga_Model_SubItems_SubProjectEmployee extends \Erga_Model_SubItems_SubProjectEmployee implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function get_subproject()
    {
        $this->__load();
        return parent::get_subproject();
    }

    public function set_subproject($_subproject)
    {
        $this->__load();
        return parent::set_subproject($_subproject);
    }

    public function get_project()
    {
        $this->__load();
        return parent::get_project();
    }

    public function set_project($_project)
    {
        $this->__load();
        return parent::set_project($_project);
    }

    public function getProjectName()
    {
        $this->__load();
        return parent::getProjectName();
    }

    public function wasActive($month = NULL, $year = NULL)
    {
        $this->__load();
        return parent::wasActive($month, $year);
    }

    public function get_employee()
    {
        $this->__load();
        return parent::get_employee();
    }

    public function set_employee(\Application_Model_Employee $_employee)
    {
        $this->__load();
        return parent::set_employee($_employee);
    }

    public function get_refnumapproved()
    {
        $this->__load();
        return parent::get_refnumapproved();
    }

    public function set_refnumapproved($_refnumapproved)
    {
        $this->__load();
        return parent::set_refnumapproved($_refnumapproved);
    }

    public function get_contractnum()
    {
        $this->__load();
        return parent::get_contractnum();
    }

    public function set_contractnum($_contractnum)
    {
        $this->__load();
        return parent::set_contractnum($_contractnum);
    }

    public function get_startdate()
    {
        $this->__load();
        return parent::get_startdate();
    }

    public function set_startdate($_startdate)
    {
        $this->__load();
        return parent::set_startdate($_startdate);
    }

    public function get_enddate()
    {
        $this->__load();
        return parent::get_enddate();
    }

    public function set_enddate($_enddate)
    {
        $this->__load();
        return parent::set_enddate($_enddate);
    }

    public function get_manmonths()
    {
        $this->__load();
        return parent::get_manmonths();
    }

    public function set_manmonths($_manmonths)
    {
        $this->__load();
        return parent::set_manmonths($_manmonths);
    }

    public function get_amount()
    {
        $this->__load();
        return parent::get_amount();
    }

    public function set_amount($_amount)
    {
        $this->__load();
        return parent::set_amount($_amount);
    }

    public function get_amountAsFloat()
    {
        $this->__load();
        return parent::get_amountAsFloat();
    }

    public function get_category()
    {
        $this->__load();
        return parent::get_category();
    }

    public function set_category($_category)
    {
        $this->__load();
        return parent::set_category($_category);
    }

    public function get_specialty()
    {
        $this->__load();
        return parent::get_specialty();
    }

    public function set_specialty($_specialty)
    {
        $this->__load();
        return parent::set_specialty($_specialty);
    }

    public function get_comments()
    {
        $this->__load();
        return parent::get_comments();
    }

    public function get_isauthor()
    {
        $this->__load();
        return parent::get_isauthor();
    }

    public function set_isauthor($_isauthor)
    {
        $this->__load();
        return parent::set_isauthor($_isauthor);
    }

    public function set_comments($_comments)
    {
        $this->__load();
        return parent::set_comments($_comments);
    }

    public function get_timesheets()
    {
        $this->__load();
        return parent::get_timesheets();
    }

    public function set_timesheets($_timesheets)
    {
        $this->__load();
        return parent::set_timesheets($_timesheets);
    }

    public function get_timesheetsApproved()
    {
        $this->__load();
        return parent::get_timesheetsApproved();
    }

    public function get_afm()
    {
        $this->__load();
        return parent::get_afm();
    }

    public function setOwner($owner)
    {
        $this->__load();
        return parent::setOwner($owner);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function get_recordid()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["_recordid"];
        }
        $this->__load();
        return parent::get_recordid();
    }

    public function set_recordid($_recordid)
    {
        $this->__load();
        return parent::set_recordid($_recordid);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function get__classname()
    {
        $this->__load();
        return parent::get__classname();
    }

    public function set__classname($__classname)
    {
        $this->__load();
        return parent::set__classname($__classname);
    }

    public function setOptions(array $options, $ignoreisvisible = false)
    {
        $this->__load();
        return parent::setOptions($options, $ignoreisvisible);
    }

    public function getOptions($onlyDbFields = true, $poptions = array (
))
    {
        $this->__load();
        return parent::getOptions($onlyDbFields, $poptions);
    }

    public function toArray($onlyDbFields = true, $recursive = false, $options = array (
))
    {
        $this->__load();
        return parent::toArray($onlyDbFields, $recursive, $options);
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function remove()
    {
        $this->__load();
        return parent::remove();
    }

    public function getMetaOptions()
    {
        $this->__load();
        return parent::getMetaOptions();
    }

    public function getOptionsAsStrings($where = 'object', $dbfieldsonly = false, $curObject = NULL, &$variables = array (
), $visited = array (
))
    {
        $this->__load();
        return parent::getOptionsAsStrings($where, $dbfieldsonly, $curObject, $variables, $visited);
    }

    public function modifySubCollection($newcollection, &$oldcollection)
    {
        $this->__load();
        return parent::modifySubCollection($newcollection, $oldcollection);
    }


    public function __sleep()
    {
        return array('__isInitialized__', '_refnumapproved', '_contractnum', '_startdate', '_enddate', '_manmonths', '_amount', '_comments', '_recordid', '_subproject', '_project', '_employee', '_category', '_specialty', '_isauthor', '_timesheets');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}