<?php

namespace DoctrineProxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Erga_Model_SubItems_SubProjectContractorProxy extends \Erga_Model_SubItems_SubProjectContractor implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function get_subproject()
    {
        $this->__load();
        return parent::get_subproject();
    }

    public function set_subproject($_subproject)
    {
        $this->__load();
        return parent::set_subproject($_subproject);
    }

    public function get_agency()
    {
        $this->__load();
        return parent::get_agency();
    }

    public function set_agency(\Application_Model_Contractor $_agency)
    {
        $this->__load();
        return parent::set_agency($_agency);
    }

    public function get_refnumapproved()
    {
        $this->__load();
        return parent::get_refnumapproved();
    }

    public function set_refnumapproved($_refnumapproved)
    {
        $this->__load();
        return parent::set_refnumapproved($_refnumapproved);
    }

    public function get_contractnum()
    {
        $this->__load();
        return parent::get_contractnum();
    }

    public function set_contractnum($_contractnum)
    {
        $this->__load();
        return parent::set_contractnum($_contractnum);
    }

    public function get_contact()
    {
        $this->__load();
        return parent::get_contact();
    }

    public function set_contact($_contact)
    {
        $this->__load();
        return parent::set_contact($_contact);
    }

    public function get_phone()
    {
        $this->__load();
        return parent::get_phone();
    }

    public function set_phone($_phone)
    {
        $this->__load();
        return parent::set_phone($_phone);
    }

    public function get_email()
    {
        $this->__load();
        return parent::get_email();
    }

    public function set_email($_email)
    {
        $this->__load();
        return parent::set_email($_email);
    }

    public function get_startdate()
    {
        $this->__load();
        return parent::get_startdate();
    }

    public function set_startdate($_startdate)
    {
        $this->__load();
        return parent::set_startdate($_startdate);
    }

    public function get_enddate()
    {
        $this->__load();
        return parent::get_enddate();
    }

    public function set_enddate($_enddate)
    {
        $this->__load();
        return parent::set_enddate($_enddate);
    }

    public function get_refnumcontract()
    {
        $this->__load();
        return parent::get_refnumcontract();
    }

    public function set_refnumcontract($_refnumcontract)
    {
        $this->__load();
        return parent::set_refnumcontract($_refnumcontract);
    }

    public function get_amount()
    {
        $this->__load();
        return parent::get_amount();
    }

    public function set_amount($_amount)
    {
        $this->__load();
        return parent::set_amount($_amount);
    }

    public function get_provisionalacceptancedate()
    {
        $this->__load();
        return parent::get_provisionalacceptancedate();
    }

    public function set_provisionalacceptancedate($_provisionalacceptancedate)
    {
        $this->__load();
        return parent::set_provisionalacceptancedate($_provisionalacceptancedate);
    }

    public function get_finalacceptancedate()
    {
        $this->__load();
        return parent::get_finalacceptancedate();
    }

    public function set_finalacceptancedate($_finalacceptancedate)
    {
        $this->__load();
        return parent::set_finalacceptancedate($_finalacceptancedate);
    }

    public function get_repaymentdate()
    {
        $this->__load();
        return parent::get_repaymentdate();
    }

    public function set_repaymentdate($_repaymentdate)
    {
        $this->__load();
        return parent::set_repaymentdate($_repaymentdate);
    }

    public function get_comments()
    {
        $this->__load();
        return parent::get_comments();
    }

    public function set_comments($_comments)
    {
        $this->__load();
        return parent::set_comments($_comments);
    }

    public function get_contractstage()
    {
        $this->__load();
        return parent::get_contractstage();
    }

    public function setOwner($owner)
    {
        $this->__load();
        return parent::setOwner($owner);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function get_recordid()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["_recordid"];
        }
        $this->__load();
        return parent::get_recordid();
    }

    public function set_recordid($_recordid)
    {
        $this->__load();
        return parent::set_recordid($_recordid);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function get__classname()
    {
        $this->__load();
        return parent::get__classname();
    }

    public function set__classname($__classname)
    {
        $this->__load();
        return parent::set__classname($__classname);
    }

    public function setOptions(array $options, $ignoreisvisible = false)
    {
        $this->__load();
        return parent::setOptions($options, $ignoreisvisible);
    }

    public function getOptions($onlyDbFields = true, $poptions = array (
))
    {
        $this->__load();
        return parent::getOptions($onlyDbFields, $poptions);
    }

    public function toArray($onlyDbFields = true, $recursive = false, $options = array (
))
    {
        $this->__load();
        return parent::toArray($onlyDbFields, $recursive, $options);
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function remove()
    {
        $this->__load();
        return parent::remove();
    }

    public function getMetaOptions()
    {
        $this->__load();
        return parent::getMetaOptions();
    }

    public function getOptionsAsStrings($where = 'object', $dbfieldsonly = false, $curObject = NULL, &$variables = array (
), $visited = array (
))
    {
        $this->__load();
        return parent::getOptionsAsStrings($where, $dbfieldsonly, $curObject, $variables, $visited);
    }

    public function modifySubCollection($newcollection, &$oldcollection)
    {
        $this->__load();
        return parent::modifySubCollection($newcollection, $oldcollection);
    }


    public function __sleep()
    {
        return array('__isInitialized__', '_subproject', '_agency', '_refnumapproved', '_contractnum', '_contact', '_phone', '_email', '_startdate', '_enddate', '_refnumcontract', '_amount', '_provisionalacceptancedate', '_finalacceptancedate', '_repaymentdate', '_comments', '_recordid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}