<?php

namespace DoctrineProxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Erga_Model_SubItems_DeliverableProxy extends \Erga_Model_SubItems_Deliverable implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function get_workpackage()
    {
        $this->__load();
        return parent::get_workpackage();
    }

    public function set_workpackage($_workpackage)
    {
        $this->__load();
        return parent::set_workpackage($_workpackage);
    }

    public function get_codename()
    {
        $this->__load();
        return parent::get_codename();
    }

    public function set_codename($_codename)
    {
        $this->__load();
        return parent::set_codename($_codename);
    }

    public function get_title()
    {
        $this->__load();
        return parent::get_title();
    }

    public function set_title($_title)
    {
        $this->__load();
        return parent::set_title($_title);
    }

    public function get_fulltitle()
    {
        $this->__load();
        return parent::get_fulltitle();
    }

    public function get_shorttitle()
    {
        $this->__load();
        return parent::get_shorttitle();
    }

    public function get_authors()
    {
        $this->__load();
        return parent::get_authors();
    }

    public function set_authors($_authors)
    {
        $this->__load();
        return parent::set_authors($_authors);
    }

    public function get_contractor()
    {
        $this->__load();
        return parent::get_contractor();
    }

    public function set_contractor($_contractor)
    {
        $this->__load();
        return parent::set_contractor($_contractor);
    }

    public function get_authorSurnamesAs2dArray()
    {
        $this->__load();
        return parent::get_authorSurnamesAs2dArray();
    }

    public function get_authorFromEmployee(\Erga_Model_SubItems_SubProjectEmployee $employee)
    {
        $this->__load();
        return parent::get_authorFromEmployee($employee);
    }

    public function get_amount(\Erga_Model_PersonnelCategories_PersonnelCategory $category = NULL)
    {
        $this->__load();
        return parent::get_amount($category);
    }

    public function set_amount($_amount)
    {
        $this->__load();
        return parent::set_amount($_amount);
    }

    public function get_amountAsFloat()
    {
        $this->__load();
        return parent::get_amountAsFloat();
    }

    public function get_startdate()
    {
        $this->__load();
        return parent::get_startdate();
    }

    public function set_startdate($_startdate)
    {
        $this->__load();
        return parent::set_startdate($_startdate);
    }

    public function get_enddate()
    {
        $this->__load();
        return parent::get_enddate();
    }

    public function set_enddate($_enddate)
    {
        $this->__load();
        return parent::set_enddate($_enddate);
    }

    public function get_assignmentapprovaldate()
    {
        $this->__load();
        return parent::get_assignmentapprovaldate();
    }

    public function set_assignmentapprovaldate($_assignapprovaldate)
    {
        $this->__load();
        return parent::set_assignmentapprovaldate($_assignapprovaldate);
    }

    public function get_completionapprovaldate()
    {
        $this->__load();
        return parent::get_completionapprovaldate();
    }

    public function set_completionapprovaldate($_completionapprovaldate)
    {
        $this->__load();
        return parent::set_completionapprovaldate($_completionapprovaldate);
    }

    public function get_comments()
    {
        $this->__load();
        return parent::get_comments();
    }

    public function set_comments($_comments)
    {
        $this->__load();
        return parent::set_comments($_comments);
    }

    public function get_timesheetactivities()
    {
        $this->__load();
        return parent::get_timesheetactivities();
    }

    public function set_timesheetactivities($_timesheetactivities)
    {
        $this->__load();
        return parent::set_timesheetactivities($_timesheetactivities);
    }

    public function get_limits()
    {
        $this->__load();
        return parent::get_limits();
    }

    public function set_limits($_limits)
    {
        $this->__load();
        return parent::set_limits($_limits);
    }

    public function get__duration()
    {
        $this->__load();
        return parent::get__duration();
    }

    public function isComplete()
    {
        $this->__load();
        return parent::isComplete();
    }

    public function isOverdue()
    {
        $this->__load();
        return parent::isOverdue();
    }

    public function hasOverdueDeliverables()
    {
        $this->__load();
        return parent::hasOverdueDeliverables();
    }

    public function setOwner($owner)
    {
        $this->__load();
        return parent::setOwner($owner);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function get_recordid()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["_recordid"];
        }
        $this->__load();
        return parent::get_recordid();
    }

    public function set_recordid($_recordid)
    {
        $this->__load();
        return parent::set_recordid($_recordid);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function get__classname()
    {
        $this->__load();
        return parent::get__classname();
    }

    public function set__classname($__classname)
    {
        $this->__load();
        return parent::set__classname($__classname);
    }

    public function setOptions(array $options, $ignoreisvisible = false)
    {
        $this->__load();
        return parent::setOptions($options, $ignoreisvisible);
    }

    public function getOptions($onlyDbFields = true, $poptions = array (
))
    {
        $this->__load();
        return parent::getOptions($onlyDbFields, $poptions);
    }

    public function toArray($onlyDbFields = true, $recursive = false, $options = array (
))
    {
        $this->__load();
        return parent::toArray($onlyDbFields, $recursive, $options);
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function remove()
    {
        $this->__load();
        return parent::remove();
    }

    public function getMetaOptions()
    {
        $this->__load();
        return parent::getMetaOptions();
    }

    public function getOptionsAsStrings($where = 'object', $dbfieldsonly = false, $curObject = NULL, &$variables = array (
), $visited = array (
))
    {
        $this->__load();
        return parent::getOptionsAsStrings($where, $dbfieldsonly, $curObject, $variables, $visited);
    }

    public function modifySubCollection($newcollection, &$oldcollection)
    {
        $this->__load();
        return parent::modifySubCollection($newcollection, $oldcollection);
    }


    public function __sleep()
    {
        return array('__isInitialized__', '_workpackage', '_authors', '_contractor', '_codename', '_title', '_amount', '_startdate', '_enddate', '_assignmentapprovaldate', '_completionapprovaldate', '_comments', '_timesheetactivities', '_limits', '_recordid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}